#!/usr/bin/env python3
"""
env_manager.py - 環境變量管理工具
管理和驗證環境變量配置
"""

import os
import sys
import argparse
from pathlib import Path
from typing import Dict, List, Optional, Set
import re


class EnvManager:
    """環境變量管理器"""

    def __init__(self, env_file: str = '.env'):
        self.env_file = Path(env_file)
        self.variables = {}
        self.required_vars = set()
        self.optional_vars = set()

    def load(self) -> Dict[str, str]:
        """加載 .env 文件"""
        if not self.env_file.exists():
            print(f"警告: {self.env_file} 不存在")
            return {}

        with open(self.env_file, 'r', encoding='utf-8') as f:
            for line_num, line in enumerate(f, 1):
                line = line.strip()

                # 跳過空行和註解
                if not line or line.startswith('#'):
                    continue

                # 解析變量
                match = re.match(r'^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$', line)
                if match:
                    key, value = match.groups()
                    # 移除引號
                    value = value.strip('"\'')
                    self.variables[key] = value
                else:
                    print(f"警告: 第 {line_num} 行格式無效: {line}")

        return self.variables

    def save(self, variables: Optional[Dict[str, str]] = None):
        """儲存變量到 .env 文件"""
        if variables:
            self.variables = variables

        lines = []

        # 添加標題註解
        lines.append("# Environment Variables")
        lines.append(f"# Generated by env_manager.py")
        lines.append("")

        # 寫入變量
        for key, value in sorted(self.variables.items()):
            # 如果值包含空格或特殊字符，添加引號
            if ' ' in value or any(c in value for c in ['$', '#', '"', "'"]):
                value = f'"{value}"'
            lines.append(f"{key}={value}")

        with open(self.env_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines) + '\n')

        print(f"✓ 已儲存到 {self.env_file}")

    def set_var(self, key: str, value: str):
        """設置變量"""
        if not re.match(r'^[A-Za-z_][A-Za-z0-9_]*$', key):
            raise ValueError(f"無效的變量名: {key}")

        self.variables[key] = value
        print(f"✓ 已設置 {key}")

    def get_var(self, key: str) -> Optional[str]:
        """獲取變量"""
        return self.variables.get(key)

    def delete_var(self, key: str):
        """刪除變量"""
        if key in self.variables:
            del self.variables[key]
            print(f"✓ 已刪除 {key}")
        else:
            print(f"警告: {key} 不存在")

    def list_vars(self, show_values: bool = False):
        """列出所有變量"""
        if not self.variables:
            print("沒有環境變量")
            return

        print(f"\n環境變量 ({len(self.variables)}):")
        print("="*60)

        for key in sorted(self.variables.keys()):
            if show_values:
                value = self.variables[key]
                # 隱藏敏感值
                if self._is_sensitive(key):
                    value = '*' * 8
                print(f"{key} = {value}")
            else:
                print(f"- {key}")

    def validate(self, required: Optional[List[str]] = None) -> bool:
        """驗證環境變量"""
        print("\n驗證環境變量...")

        missing = []
        invalid = []

        # 檢查必需的變量
        if required:
            for var in required:
                if var not in self.variables:
                    missing.append(var)
                elif not self.variables[var]:
                    invalid.append((var, "值為空"))

        # 檢查敏感變量
        for key, value in self.variables.items():
            if self._is_sensitive(key):
                if len(value) < 8:
                    invalid.append((key, "值過短，建議至少 8 個字符"))

        # 報告結果
        all_valid = not missing and not invalid

        if missing:
            print(f"\n❌ 缺少必需的變量:")
            for var in missing:
                print(f"  - {var}")

        if invalid:
            print(f"\n⚠️  無效的變量:")
            for var, reason in invalid:
                print(f"  - {var}: {reason}")

        if all_valid:
            print("✓ 所有環境變量都有效")

        return all_valid

    def generate_template(self, output_file: str = '.env.example'):
        """生成範本文件"""
        lines = [
            "# Environment Variables Template",
            "# Copy this file to .env and fill in the values",
            "",
        ]

        for key in sorted(self.variables.keys()):
            # 添加描述註解
            if self._is_sensitive(key):
                lines.append(f"# {key} - Sensitive: Use a secure value")
            else:
                lines.append(f"# {key}")

            # 添加範例值（空值或佔位符）
            if self._is_sensitive(key):
                lines.append(f"{key}=your_{key.lower()}_here")
            else:
                lines.append(f"{key}=")

            lines.append("")

        output_path = Path(output_file)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))

        print(f"✓ 已生成範本: {output_file}")

    def check_security(self) -> List[Dict]:
        """安全檢查"""
        issues = []

        # 檢查文件權限
        if self.env_file.exists():
            stat = self.env_file.stat()
            mode = stat.st_mode

            if mode & 0o044:  # 其他用戶可讀
                issues.append({
                    'severity': 'high',
                    'message': f'{self.env_file} 對其他用戶可讀',
                    'recommendation': f'執行: chmod 600 {self.env_file}'
                })

        # 檢查敏感變量
        for key, value in self.variables.items():
            if self._is_sensitive(key):
                # 檢查弱密碼
                if len(value) < 12:
                    issues.append({
                        'severity': 'medium',
                        'message': f'{key} 的值過短',
                        'recommendation': '使用至少 12 個字符的強密碼'
                    })

                # 檢查簡單密碼
                if value.lower() in ['password', '123456', 'admin', 'root']:
                    issues.append({
                        'severity': 'critical',
                        'message': f'{key} 使用了弱密碼',
                        'recommendation': '使用強密碼'
                    })

        # 檢查是否在 .gitignore 中
        gitignore = Path('.gitignore')
        if gitignore.exists():
            with open(gitignore, 'r') as f:
                content = f.read()
                if '.env' not in content:
                    issues.append({
                        'severity': 'high',
                        'message': '.env 未在 .gitignore 中',
                        'recommendation': '添加 .env 到 .gitignore'
                    })
        else:
            issues.append({
                'severity': 'medium',
                'message': '未找到 .gitignore 文件',
                'recommendation': '創建 .gitignore 並添加 .env'
            })

        return issues

    def compare(self, other_file: str):
        """比較兩個 .env 文件"""
        other = EnvManager(other_file)
        other.load()

        current_vars = set(self.variables.keys())
        other_vars = set(other.variables.keys())

        only_current = current_vars - other_vars
        only_other = other_vars - current_vars
        common = current_vars & other_vars

        print(f"\n比較 {self.env_file} 和 {other_file}:")
        print("="*60)

        if only_current:
            print(f"\n僅在 {self.env_file}:")
            for var in sorted(only_current):
                print(f"  + {var}")

        if only_other:
            print(f"\n僅在 {other_file}:")
            for var in sorted(only_other):
                print(f"  - {var}")

        if common:
            print(f"\n共同變量 ({len(common)}):")
            different = []
            for var in sorted(common):
                if self.variables[var] != other.variables[var]:
                    different.append(var)

            if different:
                print(f"  值不同的變量:")
                for var in different:
                    print(f"    • {var}")
            else:
                print("  所有值都相同")

    def export_to_shell(self):
        """導出為 shell 腳本"""
        lines = ["#!/bin/bash", "# Auto-generated environment variables", ""]

        for key, value in sorted(self.variables.items()):
            # 轉義特殊字符
            value = value.replace('"', '\\"')
            lines.append(f'export {key}="{value}"')

        return '\n'.join(lines)

    def _is_sensitive(self, key: str) -> bool:
        """檢查是否為敏感變量"""
        sensitive_keywords = [
            'password', 'secret', 'key', 'token', 'api',
            'auth', 'credential', 'private', 'pass'
        ]
        key_lower = key.lower()
        return any(keyword in key_lower for keyword in sensitive_keywords)


def main():
    """主函數"""
    parser = argparse.ArgumentParser(
        description="環境變量管理工具 - 管理和驗證環境變量配置",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
範例:
  %(prog)s list                          # 列出所有變量
  %(prog)s list --show-values            # 列出變量及其值
  %(prog)s set DB_HOST localhost         # 設置變量
  %(prog)s get DB_HOST                   # 獲取變量
  %(prog)s delete OLD_VAR                # 刪除變量
  %(prog)s validate --required DB_HOST,DB_PORT  # 驗證必需變量
  %(prog)s template                      # 生成範本文件
  %(prog)s security                      # 安全檢查
  %(prog)s compare .env.production       # 比較環境文件
        """
    )

    parser.add_argument('command',
                       choices=['list', 'set', 'get', 'delete', 'validate',
                               'template', 'security', 'compare', 'export'],
                       help='要執行的命令')
    parser.add_argument('args', nargs='*', help='命令參數')
    parser.add_argument('--env-file', default='.env',
                       help='.env 文件路徑（預設: .env）')
    parser.add_argument('--show-values', action='store_true',
                       help='顯示變量值')
    parser.add_argument('--required', help='必需的變量（逗號分隔）')
    parser.add_argument('--output', '-o', help='輸出文件路徑')

    args = parser.parse_args()

    manager = EnvManager(env_file=args.env_file)

    try:
        # 對於大多數命令，先加載現有變量
        if args.command != 'template':
            manager.load()

        if args.command == 'list':
            manager.list_vars(show_values=args.show_values)

        elif args.command == 'set':
            if len(args.args) < 2:
                print("錯誤: 需要變量名和值", file=sys.stderr)
                sys.exit(1)
            key, value = args.args[0], ' '.join(args.args[1:])
            manager.set_var(key, value)
            manager.save()

        elif args.command == 'get':
            if not args.args:
                print("錯誤: 需要變量名", file=sys.stderr)
                sys.exit(1)
            key = args.args[0]
            value = manager.get_var(key)
            if value is not None:
                print(f"{key}={value}")
            else:
                print(f"錯誤: {key} 不存在", file=sys.stderr)
                sys.exit(1)

        elif args.command == 'delete':
            if not args.args:
                print("錯誤: 需要變量名", file=sys.stderr)
                sys.exit(1)
            key = args.args[0]
            manager.delete_var(key)
            manager.save()

        elif args.command == 'validate':
            required = args.required.split(',') if args.required else []
            valid = manager.validate(required=required)
            sys.exit(0 if valid else 1)

        elif args.command == 'template':
            output = args.output or '.env.example'
            if not manager.variables:
                manager.load()  # 嘗試加載現有變量
            if manager.variables:
                manager.generate_template(output)
            else:
                print("警告: 沒有變量可以生成範本", file=sys.stderr)

        elif args.command == 'security':
            issues = manager.check_security()
            if issues:
                print("\n🔒 安全檢查結果:")
                print("="*60)
                for issue in issues:
                    severity = issue['severity'].upper()
                    print(f"\n[{severity}] {issue['message']}")
                    print(f"  💡 建議: {issue['recommendation']}")
                sys.exit(1 if any(i['severity'] in ['critical', 'high'] for i in issues) else 0)
            else:
                print("✓ 未發現安全問題")

        elif args.command == 'compare':
            if not args.args:
                print("錯誤: 需要要比較的文件路徑", file=sys.stderr)
                sys.exit(1)
            manager.compare(args.args[0])

        elif args.command == 'export':
            script = manager.export_to_shell()
            if args.output:
                with open(args.output, 'w') as f:
                    f.write(script)
                print(f"✓ 已導出到 {args.output}")
            else:
                print(script)

    except Exception as e:
        print(f"\n錯誤: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == '__main__':
    main()
