// 示範食譜數據
const sampleRecipes = [
  {
    'id': '1',
    'title': '番茄炒蛋',
    'description': '經典家常菜，簡單美味',
    'imageUrl': 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=800',
    'prepTime': 10,
    'cookTime': 15,
    'servings': 2,
    'difficulty': 'easy',
    'category': 'chinese',
    'calories': 180,
    'tags': ['家常菜', '快手菜'],
    'ingredients': [
      '雞蛋 3顆',
      '番茄 2顆',
      '蔥花 適量',
      '鹽 1/2茶匙',
      '糖 1/4茶匙',
      '油 2大匙',
    ],
    'steps': [
      '番茄洗淨切塊，雞蛋打散',
      '熱鍋加油，炒蛋至七分熟盛出',
      '原鍋炒番茄至軟爛',
      '加入炒好的蛋、調味料',
      '快速翻炒均勻，撒上蔥花即可',
    ],
  },
  {
    'id': '2',
    'title': '義大利麵',
    'description': '濃郁奶油白醬義大利麵',
    'imageUrl': 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
    'prepTime': 15,
    'cookTime': 25,
    'servings': 2,
    'difficulty': 'medium',
    'category': 'western',
    'calories': 520,
    'tags': ['西式', '主食'],
    'ingredients': [
      '義大利麵 200g',
      '培根 100g',
      '鮮奶油 200ml',
      '帕瑪森起司 50g',
      '大蒜 3瓣',
      '橄欖油 2大匙',
      '黑胡椒 適量',
    ],
    'steps': [
      '煮一鍋水，加鹽煮義大利麵8-10分鐘',
      '培根切條，大蒜切末',
      '熱鍋加橄欖油，炒香大蒜和培根',
      '加入鮮奶油煮滾',
      '放入煮好的麵條和起司粉拌勻',
      '撒上黑胡椒，即可享用',
    ],
  },
  {
    'id': '3',
    'title': '日式咖哩飯',
    'description': '香濃美味的日式咖哩',
    'imageUrl': 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800',
    'prepTime': 20,
    'cookTime': 40,
    'servings': 4,
    'difficulty': 'medium',
    'category': 'japanese',
    'calories': 450,
    'tags': ['日式', '咖哩'],
    'ingredients': [
      '咖哩塊 5塊',
      '雞腿肉 300g',
      '馬鈴薯 2顆',
      '紅蘿蔔 1條',
      '洋蔥 1顆',
      '水 800ml',
    ],
    'steps': [
      '雞肉、蔬菜切塊',
      '熱鍋炒香洋蔥和雞肉',
      '加入馬鈴薯和紅蘿蔔',
      '倒入水煮滾，轉小火燉煮20分鐘',
      '關火加入咖哩塊攪拌至溶解',
      '再次煮滾，搭配白飯享用',
    ],
  },
  {
    'id': '4',
    'title': '巧克力布朗尼',
    'description': '濃郁的巧克力蛋糕',
    'imageUrl': 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=800',
    'prepTime': 20,
    'cookTime': 30,
    'servings': 8,
    'difficulty': 'medium',
    'category': 'dessert',
    'calories': 350,
    'tags': ['甜點', '烘焙'],
    'ingredients': [
      '黑巧克力 200g',
      '奶油 150g',
      '砂糖 150g',
      '雞蛋 3顆',
      '低筋麵粉 100g',
      '可可粉 30g',
    ],
    'steps': [
      '巧克力和奶油隔水加熱融化',
      '加入砂糖攪拌均勻',
      '分次加入雞蛋拌勻',
      '篩入麵粉和可可粉，輕拌',
      '倒入烤模，180度烤25-30分鐘',
      '放涼後切塊享用',
    ],
  },
  {
    'id': '5',
    'title': '凱薩沙拉',
    'description': '清爽健康的凱薩沙拉',
    'imageUrl': 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800',
    'prepTime': 15,
    'cookTime': 0,
    'servings': 2,
    'difficulty': 'easy',
    'category': 'healthy',
    'calories': 280,
    'tags': ['健康', '沙拉', '素食'],
    'ingredients': [
      '蘿蔓生菜 200g',
      '帕瑪森起司 30g',
      '麵包丁 50g',
      '凱薩醬 3大匙',
      '檸檬汁 1茶匙',
    ],
    'steps': [
      '生菜洗淨撕成小片',
      '麵包丁烤至金黃酥脆',
      '起司刨成薄片',
      '所有食材放入大碗',
      '淋上凱薩醬和檸檬汁',
      '拌勻即可享用',
    ],
  },
];
